tracker:
  name: jdbc
  extension: "sql"
  separator: ";"
  params:
    driver: "org.postgresql.Driver"
    host: "127.0.0.1"
    port: "5432"
    username: "postgres"
    password: "password"
    database: "postgres"
    schema: "executor"
    table: jdbc_migrations
    app_name: "cassandra-demo"
    team_name: "default"
    create_schema: "true"
    ignore_unclean_state: "false"

executor:
  source: "$HOME/dev/projects/data-pipelines/typeboot/typeboot-spec/output/cql"
  provider:
    name: cassandra
    extension: "cql.j2"
    separator: ";"
    params:
      contact_points: "127.0.0.1"
      port: "9042"
      ssl: "false"
      username: "cassandra"
      #password can be text or can start with fs: for file based passwords
      password: "cassandra"
      dc: "dc1"
      truststore_path: ""
      truststore_password: "cassandra"
      timeout_in_seconds: "10"
      consistency: "ONE"

vars:
  keyspace: customer
